---
replicaCount: 3
namespace: hari
fullnameOverride: mywebapp
imagePullSecrets:
- name: ecr-mywebapp
containers:
- name: mywebapp
  image:
    repository: 550515022371.dkr.ecr.eu-west-1.amazonaws.com/mywebapp
    tag: v3.0
    pullPolicy: IfNotPresent 
  env:
  - name: GREET_VAR
    value: "Hari Kumar Subramani"
  port: 5000
  securityContext: {}
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 150m
      memory: 100Mi

serviceAccount:
  create: true
  name: "mywebapp"

service:
  type: ClusterIP
  port: 80



autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

ingress:
  enabled: true
  annotations: {} 
  gateway: 
  -  istio-external-gateway
  hosts: 
  - "hari.pltworkshop5.com"
  httpRoutes:    
  - match:
    - uri:
        prefix: /
    route:
    - destination: 
        host: "mywebapp.hari.svc.cluster.local" 
        port:
          number: 80
