{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mywebapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- with .Values.ingress.hosts }}
  hosts:
  {{- toYaml . | nindent 2 }}  
  {{- end }}
  {{- with .Values.ingress.gateway }}
  gateways:
  {{- toYaml . | nindent 2 }}  
  {{- end }}
  {{- with .Values.ingress.httpRoutes }}
  http:
  {{- toYaml . | nindent 2 }}  
  {{- end }}
{{- end }}